[package]
name = "token_scale_ui_proxy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.2.0"
borsh = "1.5.1"
spl-token-2022 = "6.0.0"
thiserror = "1.0.69"

[dev-dependencies]
litesvm = "0.6.1"
solana-sdk = "2.2.0"
spl-token = "6.0.0"
